// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: gRPC/chittychat.proto

package gRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatClient is the client API for ChittyChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittyChatClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_PublishClient, error)
	Broadcast(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_BroadcastClient, error)
	Join(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_JoinClient, error)
}

type chittyChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatClient(cc grpc.ClientConnInterface) ChittyChatClient {
	return &chittyChatClient{cc}
}

func (c *chittyChatClient) Publish(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChat_ServiceDesc.Streams[0], "/proto.ChittyChat/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatPublishClient{stream}
	return x, nil
}

type ChittyChat_PublishClient interface {
	Send(*ChatReq) error
	CloseAndRecv() (*ChatReply, error)
	grpc.ClientStream
}

type chittyChatPublishClient struct {
	grpc.ClientStream
}

func (x *chittyChatPublishClient) Send(m *ChatReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatPublishClient) CloseAndRecv() (*ChatReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ChatReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chittyChatClient) Broadcast(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_BroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChat_ServiceDesc.Streams[1], "/proto.ChittyChat/Broadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatBroadcastClient{stream}
	return x, nil
}

type ChittyChat_BroadcastClient interface {
	Send(*Participant) error
	Recv() (*ChatReply, error)
	grpc.ClientStream
}

type chittyChatBroadcastClient struct {
	grpc.ClientStream
}

func (x *chittyChatBroadcastClient) Send(m *Participant) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatBroadcastClient) Recv() (*ChatReply, error) {
	m := new(ChatReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chittyChatClient) Join(ctx context.Context, opts ...grpc.CallOption) (ChittyChat_JoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChat_ServiceDesc.Streams[2], "/proto.ChittyChat/Join", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatJoinClient{stream}
	return x, nil
}

type ChittyChat_JoinClient interface {
	Send(*Participant) error
	CloseAndRecv() (*JoinReply, error)
	grpc.ClientStream
}

type chittyChatJoinClient struct {
	grpc.ClientStream
}

func (x *chittyChatJoinClient) Send(m *Participant) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatJoinClient) CloseAndRecv() (*JoinReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(JoinReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServer is the server API for ChittyChat service.
// All implementations must embed UnimplementedChittyChatServer
// for forward compatibility
type ChittyChatServer interface {
	Publish(ChittyChat_PublishServer) error
	Broadcast(ChittyChat_BroadcastServer) error
	Join(ChittyChat_JoinServer) error
	mustEmbedUnimplementedChittyChatServer()
}

// UnimplementedChittyChatServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServer struct {
}

func (UnimplementedChittyChatServer) Publish(ChittyChat_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedChittyChatServer) Broadcast(ChittyChat_BroadcastServer) error {
	return status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedChittyChatServer) Join(ChittyChat_JoinServer) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedChittyChatServer) mustEmbedUnimplementedChittyChatServer() {}

// UnsafeChittyChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServer will
// result in compilation errors.
type UnsafeChittyChatServer interface {
	mustEmbedUnimplementedChittyChatServer()
}

func RegisterChittyChatServer(s grpc.ServiceRegistrar, srv ChittyChatServer) {
	s.RegisterService(&ChittyChat_ServiceDesc, srv)
}

func _ChittyChat_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServer).Publish(&chittyChatPublishServer{stream})
}

type ChittyChat_PublishServer interface {
	SendAndClose(*ChatReply) error
	Recv() (*ChatReq, error)
	grpc.ServerStream
}

type chittyChatPublishServer struct {
	grpc.ServerStream
}

func (x *chittyChatPublishServer) SendAndClose(m *ChatReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatPublishServer) Recv() (*ChatReq, error) {
	m := new(ChatReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChittyChat_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServer).Broadcast(&chittyChatBroadcastServer{stream})
}

type ChittyChat_BroadcastServer interface {
	Send(*ChatReply) error
	Recv() (*Participant, error)
	grpc.ServerStream
}

type chittyChatBroadcastServer struct {
	grpc.ServerStream
}

func (x *chittyChatBroadcastServer) Send(m *ChatReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatBroadcastServer) Recv() (*Participant, error) {
	m := new(Participant)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChittyChat_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServer).Join(&chittyChatJoinServer{stream})
}

type ChittyChat_JoinServer interface {
	SendAndClose(*JoinReply) error
	Recv() (*Participant, error)
	grpc.ServerStream
}

type chittyChatJoinServer struct {
	grpc.ServerStream
}

func (x *chittyChatJoinServer) SendAndClose(m *JoinReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatJoinServer) Recv() (*Participant, error) {
	m := new(Participant)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChat_ServiceDesc is the grpc.ServiceDesc for ChittyChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittyChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChittyChat",
	HandlerType: (*ChittyChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _ChittyChat_Publish_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Broadcast",
			Handler:       _ChittyChat_Broadcast_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Join",
			Handler:       _ChittyChat_Join_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "gRPC/chittychat.proto",
}
