// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GetTime_GetTime_FullMethodName = "/getTime/GetTime"
)

// GetTimeClient is the client API for GetTime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetTimeClient interface {
	GetTime(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
}

type getTimeClient struct {
	cc grpc.ClientConnInterface
}

func NewGetTimeClient(cc grpc.ClientConnInterface) GetTimeClient {
	return &getTimeClient{cc}
}

func (c *getTimeClient) GetTime(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error) {
	out := new(TimeResponse)
	err := c.cc.Invoke(ctx, GetTime_GetTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTimeServer is the server API for GetTime service.
// All implementations must embed UnimplementedGetTimeServer
// for forward compatibility
type GetTimeServer interface {
	GetTime(context.Context, *TimeRequest) (*TimeResponse, error)
	mustEmbedUnimplementedGetTimeServer()
}

// UnimplementedGetTimeServer must be embedded to have forward compatible implementations.
type UnimplementedGetTimeServer struct {
}

func (UnimplementedGetTimeServer) GetTime(context.Context, *TimeRequest) (*TimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedGetTimeServer) mustEmbedUnimplementedGetTimeServer() {}

// UnsafeGetTimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetTimeServer will
// result in compilation errors.
type UnsafeGetTimeServer interface {
	mustEmbedUnimplementedGetTimeServer()
}

func RegisterGetTimeServer(s grpc.ServiceRegistrar, srv GetTimeServer) {
	s.RegisterService(&GetTime_ServiceDesc, srv)
}

func _GetTime_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetTimeServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetTime_GetTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetTimeServer).GetTime(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetTime_ServiceDesc is the grpc.ServiceDesc for GetTime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetTime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getTime",
	HandlerType: (*GetTimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _GetTime_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/template.proto",
}
